Terminada implementación de JWT
Rollback, vuelvo a usar autenticación Básica.
Problemas:

-POST a /auth/register:Permite hacer una solicitud POST y registra el usuario en BD pero no devuelve respuesta porque corta comunicación del servlet.

Terminal:

2024-02-22T16:29:32.140+01:00  INFO 5904 --- [nio-5050-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
Hibernate:
    insert
    into
        usuario
. . .

2024-02-22T16:29:32.839+01:00  WARN 5904 --- [nio-5050-exec-2] .w.s.m.s.DefaultHandlerExceptionResolver : Failure while trying to resolve exception [org.springframework.http.converter.HttpMessageNotReadableException]
java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.checkCommitted(ResponseFacade.java:485) ~[tomcat-embed-core-10.1.18.jar:10.1.18]
. . .

2024-02-22T16:29:32.876+01:00  INFO 5904 --- [nio-5050-exec-2] i.StatisticalLoggingSessionEventListener : Session Metrics {
    0 nanoseconds spent acquiring 0 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
. . .

2024-02-22T16:29:32.884+01:00 ERROR 5904 --- [nio-5050-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<es.agrobook.api.auth.AuthenticationResponse> es.agrobook.api.controller.AuthController.register(es.agrobook.api.auth.RegisterRequest)] with root cause

org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<es.agrobook.api.auth.AuthenticationResponse> es.agrobook.api.controller.AuthController.register(es.agrobook.api.auth.RegisterRequest)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:162) ~[spring-webmvc-6.1.3.jar:6.1.3]
. . .

2024-02-22T16:29:32.923+01:00 ERROR 5904 --- [nio-5050-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] threw exception

org.springframework.security.access.AccessDeniedException: Access Denied
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:98) ~[spring-security-web-6.2.1.jar:6.2.1]
. . .

2024-02-22T16:29:32.947+01:00 ERROR 5904 --- [nio-5050-exec-2] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]

jakarta.servlet.ServletException: Unable to handle the Spring Security Exception because the response is already committed.
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:144) ~[spring-security-web-6.2.1.jar:6.2.1]
. . .
Caused by: org.springframework.security.access.AccessDeniedException: Access Denied
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:98) ~[spring-security-web-6.2.1.jar:6.2.1]
. . .

-POST a /auth/register:Permite hacer una solicitud POST y registra el usuario en BD pero no devuelve respuesta porque corta comunicación del servlet.

Terminal:

Hibernate:
    select
        u1_0.idusuario,
. . .

2024-02-22T16:37:11.614+01:00 DEBUG 5904 --- [nio-5050-exec-1] o.h.stat.internal.StatisticsImpl         : HHH000117: HQL: [CRITERIA] select u1_0.idusuario,u1_0.apellido1,u1_0.apellido2,u1_0.asesor,u1_0.codigo_postal,u1_0.direccion,u1_0.email,u1_0.enabled,u1_0.localidad,u1_0.nif,u1_0.no_inscripcion_ropo,u1_0.nombre,u1_0.password,u1_0.provincia,u1_0.telefono_fijo,u1_0.telefono_movil,u1_0.username from usuario u1_0 where u1_0.username=?, time: 51ms, rows: 1
Hibernate:
    select
        u1_0.idusuario,
. . .

2024-02-22T16:37:12.351+01:00 DEBUG 5904 --- [nio-5050-exec-1] o.h.stat.internal.StatisticsImpl         : HHH000117: HQL: [CRITERIA] select u1_0.idusuario,u1_0.apellido1,u1_0.apellido2,u1_0.asesor,u1_0.codigo_postal,u1_0.direccion,u1_0.email,u1_0.enabled,u1_0.localidad,u1_0.nif,u1_0.no_inscripcion_ropo,u1_0.nombre,u1_0.password,u1_0.provincia,u1_0.telefono_fijo,u1_0.telefono_movil,u1_0.username from usuario u1_0 where u1_0.username=?, time: 8ms, rows: 1
2024-02-22T16:37:13.030+01:00  INFO 5904 --- [nio-5050-exec-1] i.StatisticalLoggingSessionEventListener : Session Metrics {
    63500 nanoseconds spent acquiring 1 JDBC connections;
. . .

2024-02-22T16:37:13.051+01:00  WARN 5904 --- [nio-5050-exec-1] .w.s.m.s.DefaultHandlerExceptionResolver : Failure while trying to resolve exception [org.springframework.http.converter.HttpMessageNotReadableException]

java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.checkCommitted(ResponseFacade.java:485) ~[tomcat-embed-core-10.1.18.jar:10.1.18]
. . .

2024-02-22T16:37:13.090+01:00  INFO 5904 --- [nio-5050-exec-1] i.StatisticalLoggingSessionEventListener : Session Metrics {
    0 nanoseconds spent acquiring 0 JDBC connections;
. . .

2024-02-22T16:37:13.095+01:00 ERROR 5904 --- [nio-5050-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<es.agrobook.api.auth.AuthenticationResponse> es.agrobook.api.controller.AuthController.authenticate(es.agrobook.api.auth.AuthenticationRequest)] with root cause

org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing: public org.springframework.http.ResponseEntity<es.agrobook.api.auth.AuthenticationResponse> es.agrobook.api.controller.AuthController.authenticate(es.agrobook.api.auth.AuthenticationRequest)
        at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.readWithMessageConverters(RequestResponseBodyMethodProcessor.java:162) ~[spring-webmvc-6.1.3.jar:6.1.3]
. . .

2024-02-22T16:37:13.135+01:00 ERROR 5904 --- [nio-5050-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] threw exception

org.springframework.security.access.AccessDeniedException: Access Denied
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:98) ~[spring-security-web-6.2.1.jar:6.2.1]
. . .

2024-02-22T16:37:13.157+01:00 ERROR 5904 --- [nio-5050-exec-1] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]

jakarta.servlet.ServletException: Unable to handle the Spring Security Exception because the response is already committed.
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:144) ~[spring-security-web-6.2.1.jar:6.2.1]
. . .
Caused by: org.springframework.security.access.AccessDeniedException: Access Denied
        at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:98) ~[spring-security-web-6.2.1.jar:6.2.1]
. . .